spring:
  datasource:
    url: jdbc:mariadb://localhost:6033/app_db
    username: db_user
    password: db_user_pass
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDB103Dialect
    hibernate:
      # none, create, updatew create-drop
      ddl-auto: create
    show-sql: true

    security:
      user:
        name: admin
        password: admin
        roles: manager
