spring:
  datasource:
    url: jdbc:postgresql://ec2-54-179-41-157.ap-southeast-1.compute.amazonaws.com:5432/postgres
    username: postgres
    password: changeme
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL95Dialect
    hibernate:
      # none, create, update, create-drop
      ddl-auto: create-drop
    show-sql: true

    security:
      user:
        name: admin
        password: admin
        roles: manager
